name: Gradle Build

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
  schedule:
    - cron: 0 0 * * 0
      
jobs:
  build:
    name: Gradle Test   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up OpenJDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run Gradle tests
      run: ./gradlew clean test
